name: check issue

on:
  workflow_call:
    inputs:
      triage-label:
        description: if true, adds a triage label when the issue is opened or reopened
        type: boolean
        default: false
    secrets:
      envGH:
        required: true

jobs:
  issue-first-interaction:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.envGH }}
          issue-message: 'Thanks for your contribution :fire: We will take a look asap :rocket:'

  triage-label:
    if: inputs.triage-label == true && contains(fromJson('["opened", "reopened"]'), github.event.action)
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
