name: meta reusable

on:
  workflow_call:
    secrets:
      envGH:
        required: true

env:
  PR_CHECK_TITLE_TYPES: ("opened" "edited", "synchronize", "reopened")
  PR_LABEL_TYPES: ("opened" "synchronize", "reopened", "labeled", "unlabeled)

jobs:
  check-issue:
    if: github.event_name == 'issues' && github.event.issue.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: first-interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.envGH }}
          issue-message: 'Thanks for your contribution :fire: We will take a look asap :rocket:'

  check-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:

      - name: first-interaction
        if: github.event.pull_request.action == 'opened'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.envGH }}
          pr-message: >-
            We are always happy to welcome new contributors :heart: To make things easier for everyone, please
            make sure to follow our [contribution guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md),
            check if you have already signed the [ECA](http://www.eclipse.org/legal/ecafaq.php), and
            relate this pull request to an existing issue or discussion.

      - name: title
        if: contains(env.PR_CHECK_TITLE_TYPES, github.event.pull_request.action)
        uses: deepakputhraya/action-pr-title@master
        with:
          # Match pull request titles conventional commit syntax (https://www.conventionalcommits.org/en/v1.0.0/)
          # (online tool for regex quick check: https://regex101.com/r/V5J8kh/1)
          #
          # Valid examples would be
          # - fix: resolve minor issue
          # - docs(Sample5): update docs for configuration
          # - feat(management-api)!: change path to access contract agreements
          #
          # Invalid examples would be
          # - Add cool feature
          # - Feature/some cool improvement
          # - fix: resolve minor issue.
          regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+((,|\/|\\)?\s?\w+)+\))?!?: [\S ]{1,80}[^\.]$'
          allowed_prefixes: 'build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test'
          prefix_case_sensitive: true

      - name: labels
        if: contains(env.PR_CHECK_LABEL_TYPES, github.event.pull_request.action)
        uses: agilepathway/label-checker@v1.6.51
        with:
          any_of: api,bug,build,dependencies,documentation,enhancement,no-changelog,refactoring
          repo_token: ${{ secrets.envGH }}
